name: Deploy SAM Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Build SAM App
        run: sam build

      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          sam deploy --no-confirm-changeset \
                     --stack-name task-manager-backend \
                     --capabilities CAPABILITY_IAM \
                     --region $AWS_REGION
